version: '3.7'

services:
  mongo:
    image: mongo:4.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  springevent:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo

